/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "surface-dim": "#cbdbf5",
        "inverse-primary": "#95d3ba",
        "on-primary-container": "#80bea6",
        primary: "#003527",
        "on-secondary-fixed-variant": "#304f00",
        "inverse-surface": "#213145",
        secondary: "#416900",
        "on-secondary-fixed": "#102000",
        "surface-container-highest": "#d3e4fe",
        "on-tertiary-container": "#a8b5ad",
        "on-tertiary-fixed-variant": "#3e4943",
        outline: "#707974",
        "outline-variant": "#bfc9c3",
        surface: "#f8f9ff",
        "on-primary-fixed": "#002117",
        "tertiary-fixed-dim": "#bdcac1",
        "on-error-container": "#93000a",
        "surface-container-low": "#eff4ff",
        "tertiary-container": "#3b4741",
        "surface-variant": "#d3e4fe",
        "on-error": "#ffffff",
        "surface-container-high": "#dce9ff",
        tertiary: "#25312b",
        "on-background": "#0b1c30",
        "secondary-fixed-dim": "#91db2a",
        "error-container": "#ffdad6",
        "on-surface": "#0b1c30",
        "inverse-on-surface": "#eaf1ff",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#2b6954",
        "on-tertiary-fixed": "#131e19",
        "primary-container": "#064e3b",
        "on-secondary-container": "#457000",
        "on-surface-variant": "#404944",
        "on-primary-fixed-variant": "#0b513d",
        "tertiary-fixed": "#d9e6dd",
        "secondary-container": "#acf847",
        background: "#f8f9ff",
        "secondary-fixed": "#acf847",
        "primary-fixed-dim": "#95d3ba",
        "surface-bright": "#f8f9ff",
        error: "#ba1a1a",
        "on-primary": "#ffffff",
        "surface-container": "#e5eeff",
        "primary-fixed": "#b0f0d6",
        "on-tertiary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        md: "24px",
        xl: "80px",
        "margin-desktop": "64px",
        sm: "12px",
        lg: "48px",
        xs: "4px",
        "margin-mobile": "16px",
        base: "8px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "label-sm": ["Inter"],
        "display-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg": ["Inter"],
        "label-md": ["Inter"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};